version: "3"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    expose:
      - "3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: football
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/:ro
      - my-db:/var/lib/mysql
volumes:
  my-db: